### ISSUE TITLE
Support for FlashDevelop style Regions

### ISSUE THREAD

**Issue by neilatbinkies** [vshaxe/vshaxe#179] opened 2017-10-18 11:53 UTC
HaxeDevelop has support for text based regions as follows.

	//{ Property: FavouriteCheese
	
	/**
	 * Favourite Cheese (always returns Brie)
	 */
	public var FavouriteCheese(default, never) : String = "Brie";	

	//}

I know recently that VS Code overhauled it's region handling, I was wondering how hard it would be to get this style of code folding to work out of the box?

**Comment by Gama11** [comment] 2017-10-18 12:47
"Haxe Regions" implies this is a Haxe feature, but it's really quite FlashDevelop-specific... which is why I'm not sure it's a good idea.

**Comment by nadako** [comment] 2017-10-24 22:53
I personally never use regions in any language, but I'm not opposed to supporting those. The problem is that there is no standard region syntax in Haxe currently and as @Gama11 said, supporting one arbitrary syntax is probably not a good idea.

I'm gonna close this, feel free to bring up discussions in Haxe communcation channels about the syntax. If there'll be some kind of consensus, we'll of course add support for it.

**Closed by nadako** 2017-10-24 22:53 UTC
