### ISSUE TITLE
While writing switch statements, multi-line error annoying, masks important errors

### ISSUE THREAD

**Issue by jcward** [vshaxe/vshaxe#267] opened 2018-07-17 21:32 UTC
When I'm in the process of writing a switch statement that needs to return a specific type, and I haven't finished writing the second or third clause, basically the entire screen turns red:

![image](https://user-images.githubusercontent.com/2192439/42845832-6c126c68-89d4-11e8-952b-e53025faf0b2.png)

e.g. the error position is reported as lines 7-12:
![image](https://user-images.githubusercontent.com/2192439/42846552-7f202186-89d6-11e8-893e-fa1ca7418e77.png)

This is _incredibly irritating_ :angry:  as it masks out other errors of what I'm actively working on (the lower clause), while yelling at me:

:computer:  "HEY, YOU HAVEN'T RETURNED X YET"
:angry: "Yes, I know I haven't returned X, I'm still working on it."

Is there any way we could make this error highlight only the offending case expression, e.g. line 13:7-13, as shown here:

![image](https://user-images.githubusercontent.com/2192439/42845916-9c382e28-89d4-11e8-9089-ebd4cb0c734f.png)

I realize the error Pos is probably a Haxe problem, although technically "errors masking other errors" and "screens full of red" are vshaxe problems.

For convenience:

```haxe
class Main
{
  public static function main()
  {
    var either = haxe.ds.Either.Left(123);

    return switch either {
      case Left(_):
        trace('Some logic...');
        trace('Some logic...');
        trace('Some logic...');
        true;
      case Right(_):
        // Start working here...
    }
  }
}

```

**Comment by jcward** [comment] 2018-07-17 21:51
BTW, as long as this is blocked, a workaround is to drop a null at the end of the case you're working on:

![image](https://user-images.githubusercontent.com/2192439/42847422-22411bac-89d9-11e8-9e8b-b153a4438bc3.png)

Just don't accidentally forget it. :open_mouth:

**Comment by Simn** [comment] 2018-07-18 05:45
This annoys the shit out of me in the OCaml extension, but I never had any issue with it using Haxe. I guess auto-save really makes the difference here.

For Haxe, the problem is that there's no expression position to report.

**Comment by Gama11** [comment] 2019-03-06 22:30
The UX for the most recent example here is now much better, as parser errors are now shown (with latest Haxe dev + vshaxe 2.7.0):

![](https://i.imgur.com/CHHK3bj.png)

Not much has changed for the original example with the empty `case` though, since that's not a parser error.

**Comment by Gama11** [comment] 2019-03-06 22:43
I'm moving this to a Haxe issue since there's not really much to be done about it from the vshaxe side of things: https://github.com/HaxeFoundation/haxe/issues/7947

**Closed by Gama11** 2019-03-06 22:43 UTC
Labels: blocked-haxe, diagnostics, enhancement

**Comment by Gama11** [comment] 2019-03-07 00:25
Aaand Simn already fixed it! :tada:
