### ISSUE TITLE
Goto compilation error in a haxe lib

### ISSUE THREAD

**Issue by Fl0xer** [vshaxe/vshaxe#194] opened 2017-11-10 15:27 UTC
There is a problem when we have compilation errors from a haxe lib.

I have modified a class in a haxe lib and got a compilation error. When I click on the error in the panel under my code window, I have a message saying that it's impossible to open the concerned file because VsCode can't find it. 

I think there is a problem with absolute / relative paths because the file VsCode is looking for is **file:///d:/Projects/godmode/D:/Projects/heaps/hxd/res/Image.hx**
where D:/Projects/godmode is my workspace, and D:/Projects/heaps/hxd/res/Image.hx is the file I have modified.

VsCode version : 1.17.2

**Comment by Gama11** [comment] 2017-11-10 17:17
Duplicate of #23.

**Closed by Gama11** 2017-11-10 17:17 UTC
Labels: duplicate
