### ISSUE TITLE
Feature Request: Add "Extract Function" for code refactoring

### ISSUE THREAD

**Issue by dubspeed** [vshaxe/vshaxe#632] opened 2024-08-05 13:16 UTC
# Feature Request: Extract Function
## Description

I would like to request the addition of an "Extract Function" feature to the VSHaxe. This feature is a common refactoring tool found in many modern IDEs.

## Proposed Functionality

The "Extract Function" feature should:

1. Allow users to select a block of code.
2. Create a new function containing the selected code.
3. Replace the original code block with a call to the newly created function.
4. Automatically determine parameters and return type based on variables used in the selected code.
5. Provide options for function visibility (public, private, etc.) and placement within the class.
6. Handle local variable scoping appropriately.

## Use Cases in Haxe

**Example 1: Extracting a code block from a method**

```haxe
class Calculator {
    public function calculateTotal(items:Array<Item>):Float {
        var total:Float = 0;
        
        // Selected code block to extract
        for (item in items) {
            var price = item.price;
            var quantity = item.quantity;
            total += price * quantity;
        }
        
        return total;
    }
}
```

After extraction:

```haxe
class Calculator {
    public function calculateTotal(items:Array<Item>):Float {
        var total:Float = 0;
        total = sumItemTotals(items, total);
        return total;
    }

    function sumItemTotals(items:Array<Item>, initialTotal:Float):Float {
        var total = initialTotal;
        for (item in items) {
            var price = item.price;
            var quantity = item.quantity;
            total += price * quantity;
        }
        return total;
    }
}
```

**Example 2: Extracting code with local variables**

```haxe
class UserManager {
    public function processUser(user:User) {
        var name = user.name;
        var age = user.age;
        
        // Selected code block to extract
        var greeting = "Hello, " + name;
        if (age < 18) {
            greeting += " (minor)";
        }
        trace(greeting);
       
        // ...
    }
}
```

After extraction:

```haxe
class UserManager {
    public function processUser(user:User) {
        var name = user.name;
        var age = user.age;
        
        greetUser(name, age);
        
        // ...
    }

    private function greetUser(name:String, age:Int) {
        var greeting = "Hello, " + name;
        if (age < 18) {
            greeting += " (minor)";
        }
        trace(greeting);
    }
}
```

## Benefits

- Improves code readability by breaking down large functions into smaller pieces.
- Enhances code reusability by creating separate functions for specific tasks.
- Facilitates easier testing of individual code blocks.
- Speeds up the refactoring process.

## Implementation Considerations

- The feature should integrate with Haxe's type inference system to determine function parameters and return types.
- It should handle different scopes and closures correctly, especially when dealing with local variables and class members.
- The extracted function's name should be automatically suggested, with the option for the user to modify it.
- The feature should respect Haxe's syntax and coding conventions.
- It should provide options for where to place the new function within the class (e.g., immediately after the current function, at the end of the class, etc.).

We believe this feature would enhance the productivity for Haxe developers using VSCode, and we would love to see the feature - or parts of it - being implemented in VSHaxe.

Thank you for considering this request!

**Comment by dubspeed** [comment] 2024-11-21 12:56
I tried to come up with some examples that include some Haxe features, maybe as a starting point:
https://gist.github.com/dubspeed/f0a6f21e44fcbdcba4c136adffc4f25f

Feel free to ping for more.

**Comment by AlexHaxe** [comment] 2024-11-21 15:01
thanks for taking the time to compile a collection of samples! 

just looking through them (I have yet to run them), I can see some of them should already work as indicated (depending on your selection). some of them will require two refactor operations (e.g. the last two samples). and a few come with added optimisations that would be nice to have but are a bit out of scope.
so for the first version I will leave such optimisations to the user and concentrate on trying not to break user code with a botched refactoring. which is where those test cases come in to help. can I assume they are safe to use in a MIT licensed code base?

**Comment by dubspeed** [comment] 2024-11-21 16:53
Sure, as all of those are pretty trivial in itself, feel free to use license them as you seem fit.

**Closed** 2024-12-23 15:47 UTC
Labels: haxe-foundation-partner

**Comment by ljurow** [comment] 2024-12-23 21:04
How do you trigger this in VS Code?  I don't see a "Refactor Function"
(Sorry if this is a dumb question.  I've been writing Haxe code in IntelliJ for years, but only recently started using VS Code)

**Comment by AlexHaxe** [comment] 2024-12-23 21:08
here you go: https://github.com/vshaxe/vshaxe/wiki/Code-Refactoring#extract-method

**Comment by ljurow** [comment] 2024-12-23 21:35
Thanks!  However, I don't get a "lightbulb" icon when I select code, and when I press "Ctrl+." when having code selected, I just get a "No code actions" popup.  FWIW - my haxe project is a pretty good sized working project, which VS Code can compile and run in a browser (and we have shipped to customers).

I feel like I don't have VS Code quite set up properly somehow.  I don't even get "Quick Fix" selections for when I'm missing a ";" - even though the compiler tells me the problem and points to the line.

**Comment by AlexHaxe** [comment] 2024-12-23 22:13
you'll need a `.hxml` at your project root for vshaxe to work (also vshaxe doesn't support multi-root workspaces, so only one project per instance). if that is the case then you'll need to look at OUTPUT view to see what error messages show up (see also https://github.com/vshaxe/vshaxe/wiki/Troubleshooting).

if you have a lime, ceramic, kha based project, you'll need to also install and activate the appropriate extension.

and lastly you also need to "trust" your workspace, otherwise vscode won't launch most or any extensions.

**Comment by ljurow** [comment] 2024-12-24 00:28
I'm not sure what you mean by "need a .hxml at your project root".  I have a project.xml file (which we have in a "Build" folder, and that _generates_ a .hxml in a "Deploy" folder (i.e. Deploy/html5/haxe/debug.hxml) when I compile the project.

Also, the Build, src, and Deploy folders are at the same level (to keep them out of the way of each other).  Don't think that's what you meant by "multi-root workspaces" - but it does show what appears to be 2 class paths (in Haxe output):
[RefactorCache] detected classpaths: [../../Deploy/com.masque.astralume/html5/haxe/,../../src/]

However, now that I know where to look for Haxe output errors - I found this (when I select some code and press "Ctrl+.")
```
Called from module TypeError: Cannot read properties of null (reading 'indentation')
Called from bs.calcIndentation (c:\Users\ljurow\.vscode\extensions\nadako.vshaxe-2.33.0\server\bin\server.js line 1 column 697854)
Called from ys.makeExtractMethodData (c:\Users\ljurow\.vscode\extensions\nadako.vshaxe-2.33.0\server\bin\server.js line 1 column 687080)
Called from ys.canRefactor (c:\Users\ljurow\.vscode\extensions\nadako.vshaxe-2.33.0\server\bin\server.js line 1 column 683978)
Called from zi.canRefactor (c:\Users\ljurow\.vscode\extensions\nadako.vshaxe-2.33.0\server\bin\server.js line 1 column 604711)
Called from ln.findMatchingRefactors (c:\Users\ljurow\.vscode\extensions\nadako.vshaxe-2.33.0\server\bin\server.js line 1 column 346439)
Called from ln.createCodeActions (c:\Users\ljurow\.vscode\extensions\nadako.vshaxe-2.33.0\server\bin\server.js line 1 column 345482)
Called from dn.onCodeAction (c:\Users\ljurow\.vscode\extensions\nadako.vshaxe-2.33.0\server\bin\server.js line 1 column 362353)
Called from Ui.handleRequest (c:\Users\ljurow\.vscode\extensions\nadako.vshaxe-2.33.0\server\bin\server.js line 1 column 597216)
Called from Ui.handleMessage (c:\Users\ljurow\.vscode\extensions\nadako.vshaxe-2.33.0\server\bin\server.js line 1 column 596561)
Called from Ki.onData (c:\Users\ljurow\.vscode\extensions\nadako.vshaxe-2.33.0\server\bin\server.js line 1 column 599791)

```

Thanks again for your help.  I really do appreciate it

**Comment by AlexHaxe** [comment] 2024-12-24 05:31
so basically you have a lime/openfl/flixel project and that needs vscode lime extension to work - unless you want to manually configure your build configuration in `.vscode/settings.json`, but I wouldn't recommend that. I am not sure if lime extension allows project.xml to be in a sub-folder - it probably won't auto-detect it unless you point it towards your Build folder.

your classpaths look a bit incorrect with all those `../` in front of it. it's probably what your project.xml generates, but I'm unsure if that will work because those paths will be calculated from your workspace folder and they might be incorrect from that perspective.

your error message might be a bug. to temporarily fix it create a `hxformat.json` in your workspace root with `{}` as it's content.

**Comment by ljurow** [comment] 2024-12-24 18:11
I believe the problem is the "missing" hxformat.json file.  Once I put that file in the folder where the SOURCE (haxe) file was, then the lightbulb shows up with "Extract method" and "Wrap with try...catch".  Note that I actually needed to put an hxformat.json in EACH FOLDER for the lightbulb to show up.  I.E.    src/lume/hxformat.json only makes the hx files in THAT FOLDER work.  If I want hx files in src/tools to work, I have to have a src/tools/hxformat.json file as well.

**Comment by AlexHaxe** [comment] 2024-12-25 02:13
it should suffice to have only one such file in a folder higher up, e.g. `src/hxformat.json` covers files in `src`, `src/lume`, `src/tools`, etc. putting it even higher up in your folder structure covers even more files and can even be used to span multiple projects.

it seems like the `../` classpaths in your refactor cache config work for you, it's only the null access in case of missing formatter configuration. I'll fix that in a future release. thanks for reporting!
