### ISSUE TITLE
stucks in document symbols

### ISSUE THREAD

**Issue by lublak** [vshaxe/vshaxe#360] opened 2019-06-23 20:41 UTC
Currenlty i have work om a very big macro class.
It compiles fine but if i want work with auto complete nothing works if i first look in my macro class:
`Haxe: Initializing Haxe/JSON-RPC protocol`
If i look first in an other class (like main) all works fine.
But if i open then the Macro class the "Outline" is loading and loading and the display stucks complete.

`Haxe Compiler 4.0.0-rc.3+e3df7a448`
also
`Haxe Compiler 4.0.0-rc.3+499e2728b`

**Comment by Gama11** [comment] 2019-06-23 21:28
How big is "very big"?

Can you provide the source file?

**Comment by lublak** [comment] 2019-06-24 07:39
@Gama11 over 600 lines of code.

it there a "debug" flag for it to test it myself?
I tried to comment out some of my code to check which code is create this stuck and found out:

```haxe
switch(type) { // haxe.macro.Type
  case TInst(t, params):
    switch('test') { // <- important
      case 'test':
           var test = function(exprs, o_ref) return macro [for(key => $i{exprs[0].name} in $i{o_ref}) key => ${exprs[0].expr}];
    }
  case TMono(t): // <- important
  default:
}
```

For Quick fix i add brackts to this function like this:

```haxe
switch(type) {
  case TInst(t, params):
    switch('test') { // <- important
      case 'test': var test = function(exprs, o_ref) {
        return macro [for(key => $i{exprs[0].name} in $i{o_ref}) key => ${exprs[0].expr}];
      };
    }
  case TMono(t): // <- important
  default:
}
```

**Comment by Gama11** [comment] 2019-06-24 10:39
Hm, 600 is not a lot, so I doubt it's related to size.

You could check if there's any errors in the Haxe output channel.

**Comment by lublak** [comment] 2019-06-24 17:57
No there is no error. It just stucks. If trigger the compiler to compile my project it works if i don't look at this class. (keep closed) @Gama11

**Comment by Gama11** [comment] 2019-06-24 23:32
Right.. I haven't had a chance to try yet, but I doubt the snippets you posted are enough to reproduce.

**Comment by Gama11** [comment] 2019-07-14 15:50
Looks like it's actually enough to reproduce - that piece of code seems to produce a hang in tokentree, as both haxe-formatter and document symbols have issues with this. Opened an issue there: https://github.com/HaxeCheckstyle/tokentree/issues/168

**Comment by Gama11** [comment] 2019-09-07 14:05
Will be fixed in the next release by a tokentree update.

**Closed by Gama11** 2019-09-07 14:05 UTC
Labels: bug, document-symbols
