### ISSUE TITLE
Feature Request: auto fix imports and packages name when moving files

### ISSUE THREAD

**Issue by filipp8** [vshaxe/vshaxe#454] opened 2020-08-12 07:25 UTC
The title says it all.
I find myself constantly reorganizing/refactoring code sooner or later in projects life and I always think about it twice because of the pain of fixing all the package names and imports.
I don't know if there is already a sort of file watcher or not ready to be used for this feature...

**Comment by Gama11** [comment] 2020-08-12 09:24
Duplicate of #287.

**Closed by Gama11** 2020-08-12 09:24 UTC
Labels: duplicate
