### ISSUE TITLE
Broken syntax highlighting with arrow functions

### ISSUE THREAD

**Issue by RealyUniqueName** [vshaxe/vshaxe#261] opened 2018-07-05 20:37 UTC
![broken return](http://dl3.joxi.net/drive/2018/07/05/0018/2666/1194602/02/4a3975ce05.jpg)
```haxe
class Main {

	static function job() return new Some(fn -> {
		return 10;
	});

	static function job2() {
	}
}
```

![broken next function declaration](http://dl4.joxi.net/drive/2018/07/05/0018/2666/1194602/02/2c9d609ecf.jpg)
```haxe
class Main {

	static function job() return new Some(fn -> {
		fn(10);
	});

	static function job2() {
	}
}
```

**Comment by Gama11** [comment] 2018-07-05 20:44
This seems to be a duplicate of https://github.com/vshaxe/haxe-TmLanguage/issues/3, since it works fine if `jobs()` has braces (so this isn't about arrow functions).

**Closed by Gama11** 2018-07-05 20:44 UTC
