### ISSUE TITLE
Auto-detect cache build failure after switching Haxe versions

### ISSUE THREAD

**Issue by joshtynjala** [vshaxe/vshaxe#609] opened 2023-10-16 21:07 UTC
Often, after switching from one version of Haxe to another, building the cache fails, and I need to manually delete my project's bin directory and restart VSCode. It would be nice if vshaxe could auto-detect a stale cache and ignore it so that I don't need to do anything manually.

I have needed to explain what's wrong to other Haxe users in the community more than once when they've encountered this same issue. There don't seem to be good clues to figure out why it is happening, and I probably originally figured it out through trial and error.

**Comment by AlexHaxe** [comment] 2023-10-16 21:50
I assume you are talking about OpenFl/Lime projects. so I just tried with a HaxeFlixel demo (`flixel-demos/Platformers/FlxTilemapExt`). I switched between Haxe 4.3.2, 4.3.1 and 4.2.5 back and forth (I even threw in a 4.1.5 somewhere) and tried compiling to `html5`, `hl` and `linux` targets. I didn't delete export / bin folders in-between builds and didn't encounter any cache problems (or didn't notice them). VSCode would update Haxe Dependencies view to show current Haxe version whenever I changed it.
Note: I am using Lix to switch between Haxe versions.

can you provide some steps to reproduce your issue?

**Comment by joshtynjala** [comment] 2023-10-16 22:04
Yes, OpenFL/Lime projects.

When I get some time, I'll try to figure out exact repo steps. I'm guessing it'll be something like the following, but I understand if you'd rather wait for me to find more specific steps.

1) Open an OpenFL project.
2) Build the OpenFL project.
3) Exit VSCode.
4) Install a different Haxe version.
5) Open the same project in VSCode again.

The cache failure may happen when opening the project again and the language server is initializing. It's not a failure during a build. It's something with the previous build affecting the language server's ability to provide code intelligence.

**Comment by AlexHaxe** [comment] 2023-10-16 22:17
I didn't quit VSCode when switching Haxe versions in my tests earlier. but even with restarting there is no cache error popping up. 
I can see `Haxe: Building Cache…` in status bar whenever I switch Haxe versions (without quitting) or once directly after restarting.

when restarting all flixel/openfl related imports and types start out as problems with red curly underlines. once "Building Cache" completes problem entries disappear and everything looks normal.

**Comment by joshtynjala** [comment] 2023-10-16 22:46
Okay, I'll try to figure out steps to reproduce. It often happens to me when I go back to projects that I haven't touched in a while, so I guess maybe I just assumed that it was the Haxe version. There may be other changes such as library versions changing too, or maybe a combination of both. Since I don't use Lix, I can see how library version changes might be more likely to affect my projects than yours.

**Comment by AlexHaxe** [comment] 2023-10-16 23:07
the flixel demo is a very small project with only two Haxe files. I don't usually do OpenFl based projects, it's just one that I have ready and it's confirmed to work. so I can quickly test issues against it.

I'm not sure whether Lix plays any role in me not being able to reproduce your issue, or if it is more project size or something else that I am lacking. (I mentioned Lix because people don't usually use it for OpenFl projects, since it's a bit tricky to get OpenFl/Lime tooling to work with it.)

once you have something that reproduces I can take a look and if it works for me, then it's either Lix helping or there's some hidden factor at play.

**Comment by joshtynjala** [comment] 2023-10-16 23:35
Okay, I've found one way to reproduce, I think. 

So I have Lime 8.0.2 and OpenFL 9.2.2 installed. I created a new project with _openfl create DisplayingABitmap_ (but any OpenFL project should work for this one, I think).

1) Open the OpenFL project in VSCode
2) Build project
3) Exit VSCode
4) haxelib set openfl 9.2.1 (or haxelib install openfl 9.2.1, if you don't have that version already)
5) haxelib remove openfl 9.2.2
6) Re-open project in VSCode

Here's the notification that appears:

> Unable to build cache - completion features may be slower than expected. Try fixing the error(s) and restarting the > language server.
> [Show Error] [Retry]

When you click Show Error button, this is the message in the output:

> Haxe language server started
> Haxe Path: haxe
> Using --server-connect
> Haxe connected!
> Listening on port 127.0.0.1:6000
> Failed - try fixing the error(s) and restarting the language server:
> 
> (unknown) : Type not found : openfl.utils._internal.ExtraParamsMacro

I changed the OpenFL version to 9.2.1 with Haxelib, but it seems that vshaxe is trying to find 9.2.2. I see that the Lime-generated .hxml files in _Export/html5/haxe/_ still have the 9.2.2 paths, so maybe that's a clue.

Deleting _Export_ and restarting VSCode will fix the issue.

Even if you simply run _haxelib set openfl 9.2.1_ after exiting VSCode, and you skip _haxelib remove openfl 9.2.2, it appears that vshaxe will keep using 9.2.2 for code intelligence after re-opening the project. For instance, if you do a workspace symbol search for _Sprite_, you can see 9,2,2 in the file paths. Deleting _Export_ and restarting VSCode will fix this too.

**Comment by joshtynjala** [comment] 2023-10-16 23:38
I should add that I tried switching between some Haxe versions, and I couldn't reproduce that one either. Sorry for not testing for specifics before reporting.

**Comment by AlexHaxe** [comment] 2023-10-17 08:44
vshaxe uses `.hxml` files to learn what Haxe configuration to use for completion or other display operations. changing your dependencies in a way that they cannot be resolved by Haxe any longer is an obvious build error. failing to "build cache" is only the tip of the iceberg in such a scenario.

however we are talking about OpenFl/Lime. they use `project.xml` for project configuration. only vshaxe doesn't understand that. that's when Lime extension comes in and helps out by pointing vshaxe to display arguments it can work with. as far as I'm aware Lime extenstion performs a `lime display <target>` to learn what Haxe CLI parameters to use for your current configuration. in case of an existing exports folder it will simply take the contents of `export/<target>/haxe/<debug|final|release>.hxml` and feed them into vshaxe. unfortunately those files contain absolute path names pointing to specific version numbers of each dependency. if those libs no longer exist, or if you switched your haxelib repository to use a different version as default your `.hxml` files won't reflect these changes until you recreate them from your `project.xml` (e.g. by building your project). 

so I don't think there is much the vshaxe extension can do here. you can try to see if running "Lime: Refresh Code Completion" command in VSCode fixes your issue. if it does then maybe running that command (or its code) at startup of Lime extension might be a possible fix (not sure if it has any negative side effects other than slightly delaying startup).

**Closed** 2023-10-17 14:20 UTC
