### ISSUE TITLE
VSHaxe stopped working after update

### ISSUE THREAD

**Issue by pawel-miczka** [vshaxe/vshaxe#175] opened 2017-10-01 20:54 UTC
Hi,

Well I am using Visual Studio Code 1.16.1. After update I have problems with this extension. My "Haxe dependencies" panel is empty (even stdin gone), it doesn't shows up error if I forget ; at the end of line etc. Autocompletion is working and I have Haxe 3.4.2 installed. Here's how It looks:

![vshaxe](https://user-images.githubusercontent.com/5631954/31058860-5c74d24e-a6fb-11e7-9078-cf87eca345fe.jpg)

I tried to reinstall Haxe, reinstall your ext, even reinstall VSC. Also i ran few VSC commands to restart langauge server etc.

**Comment by Gama11** [comment] 2017-10-01 21:32
>After update I have problems with this extension

After update of what?

**Comment by pawel-miczka** [comment] 2017-10-01 22:00
Visual Studio Code

**Comment by Gama11** [comment] 2017-10-02 20:27
Hm.. are you sure the VSCode update is the problem? I'm using latest vshaxe with VSCode 1.16.1 without any issues.

**Comment by pawel-miczka** [comment] 2017-10-03 06:59
:/ .. so what can cause problems? I have reinstalled VSC, VSHaxe and even whole haxe compilator. I will check on MacOS if it's working.

**Comment by Gama11** [comment] 2017-10-03 08:00
Have you tried it with a different project, to make sure it's not just a setup issue with that particular one? [This one](https://github.com/Gama11/HaxeRepro) perhaps?

>it doesn't shows up error if I forget ; at the end of line 

If you're talking about diagnostics, that's always been the case for missing semicolons: https://github.com/vshaxe/vshaxe/issues/102

>Autocompletion is working

Wait, is that a typo / do you mean autocompletion is _not_ working?

**Comment by nadako** [comment] 2017-10-24 23:22
I'll go ahead and close this, as the extension seems to be working fine for a lot of people with latest everything. Chances are there was some setup issue, for which we should look into providing better feedback to the user, but that's out of scope here.

**Comment by nadako** [comment] 2017-10-24 23:23
(of course feel free to reopen if there's more information on reproducing the situation)

**Closed by nadako** 2017-10-24 23:22 UTC
