### ISSUE TITLE
Restarting language server adds a "Haxe" message panel item each time

### ISSUE THREAD

**Issue by jeremyfa** [vshaxe/vshaxe#87] opened 2017-02-02 10:48 UTC
<img width="291" alt="capture d ecran 2017-02-02 a 11 46 25" src="https://cloud.githubusercontent.com/assets/164094/22546444/62c6f7b6-e93d-11e6-8337-00c7565c0b54.png">

Everytime the haxe server is restarted (from the command palette), one more "Haxe" item is added (see screenshot).

**Comment by nadako** [comment] 2017-02-02 10:53
That's a duplicate of #52, meaning it's probably a bug of VSCode client, I won't close this one though, since maybe we can research whether this can be worked around somehow.

**Comment by jeremyfa** [comment] 2017-02-02 10:58
Ah, didn't catch the existing issue sorry! Thanks for the quick feedback :)

**Comment by Gama11** [comment] 2017-02-02 11:16
Wow, I didn't realize this still happens.

**Comment by Gama11** [comment] 2017-05-18 16:22
Looks like this was fixed in the April release / 1.12.0. :)

**Comment by Jarrio** [comment] 2017-06-28 04:02
This appears to have returned in the newest `1.8.0` vshaxe update. It may have been reintroduced in the vscode 1.13 patch and no-one noticed.

**Comment by Gama11** [comment] 2017-06-28 07:19
Meh, looks like this was reintroduced by updating vscode-languageclient from 2.6.3 to 3.3.0...

**Comment by Gama11** [comment] 2017-06-28 07:31
The fix for https://github.com/Microsoft/vscode-languageserver-node/issues/87 still appears to be there in 3.3.0... https://github.com/Microsoft/vscode-languageserver-node/blob/release/3.3.0/client/src/client.ts#L1536-L1538. A breakpoint also hits that call when running the "Restart Language Server" command.

**Comment by Gama11** [comment] 2017-06-28 09:13
Opened a new issue: https://github.com/Microsoft/vscode-languageserver-node/issues/224

**Comment by Gama11** [comment] 2017-06-30 09:23
@nadako Should we downgrade vscode-languageclient as a temp fix in the meantime?

**Comment by nadako** [comment] 2017-06-30 09:32
maybe we should. it's not like the new version fixes anything anyway, it seems.

**Closed** 2017-06-30 10:52 UTC
Labels: blocked-vscode, bug, commands
