### ISSUE TITLE
Option to disable auto import

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#353] opened 2019-06-04 10:09 UTC
Auto import is evil, it should be much more easy to disable them ;-)

ATM it requires to go through manual settings.json editing and add manually

"haxe.codeGeneration": {
        "imports": { "enableAutoImports": false }
},

A more "top level" setting that can be directly searched/checked using modern VSCode settings would be welcome.

**Comment by Gama11** [comment] 2019-06-04 10:19
Duplicate of https://github.com/vshaxe/vshaxe/issues/238.

**Closed by Gama11** 2019-06-04 10:19 UTC
