### ISSUE TITLE
Position is shifted by one when using Haxe 4

### ISSUE THREAD

**Issue by jeremyfa** [vshaxe/vshaxe#210] opened 2018-03-09 09:30 UTC
<img width="297" alt="capture d ecran 2018-03-09 a 10 18 57" src="https://user-images.githubusercontent.com/164094/37200047-e6f61b44-2383-11e8-9c5d-9fd3202aac3c.png">

I recall having read discussions about starting positions with 1 instead of 0 in Haxe 4, which is great as it seems to be the de-facto standard, but `vshaxe` doesn't seem to handle this yet when hovering the mouse on some symbol.

I assume it is already planned to fix these but I still prefer to post an issue in case this is an oversight 🙂

**Comment by nadako** [comment] 2018-03-09 10:05
Hmm, that one should be fixed actually...

**Comment by jeremyfa** [comment] 2018-03-09 15:33
I am using haxe 4 (preview 3), but not installed globally. Just configured haxe 4 path with "haxe.executable" option in vscode. Could that change something?

I am using vshaxe from the marketplace (1.9.3, last updated November 5th 2017)

**Comment by Gama11** [comment] 2018-03-23 15:12
Do you have some non-standard setup like npm-haxe?

Vshaxe checks the Haxe version to decide whether to adjust positions or not. Sounds like somehow it thinks you're using a different Haxe version than you are?

If you're willing to build vshaxe from source, you could add some traces here:

https://github.com/vshaxe/haxe-languageserver/blob/master/src/haxeLanguageServer/helper/DisplayOffsetConverter.hx#L14

**Comment by jeremyfa** [comment] 2018-03-23 15:53
Nothing like npm-haxe on my machine, I will double check that there isn't something weird in the setup and if not will indeed add some logs to see what actually happens

**Comment by jeremyfa** [comment] 2018-03-26 07:50
As mentioned above, I have haxe 3.x installed globally, but haxe 4 binary configured in my user settings `haxe.executable` of vscode. Could it be that vshaxe mistakenly checks the globally installed haxe version instead of the configured one? That would explain the issue at least.

**Comment by Gama11** [comment] 2018-03-26 10:18
I don't think so, vshaxe should be respecting `haxe.executable` everywhere:

https://github.com/vshaxe/haxe-languageserver/blob/6dbe35f144be042cce41a33bbf9323f441321396/src/haxeLanguageServer/HaxeServer.hx#L144

**Comment by Gama11** [comment] 2018-04-08 19:45
Let us know if you find the cause or a way for us to reproduce it.

**Closed by Gama11** 2018-04-08 19:45 UTC
Labels: cant-reproduce
