### ISSUE TITLE
[feature request] override hook

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#143] opened 2017-06-29 23:06 UTC
HaxeDevelop has a nice feature that when write `override ` you'll get a list of super classes methods as completion dialog and if you choose one it automatically generate the method declaration with all arguments already typed, saves a lot of time when doing OOP.

**Comment by Gama11** [comment] 2017-06-30 07:33
Duplicate of #92.

**Closed by Gama11** 2017-06-30 07:33 UTC
