### ISSUE TITLE
No completion and bad paths when using local haxelib repo

### ISSUE THREAD

**Issue by bablukid** [vshaxe/vshaxe#209] opened 2018-03-01 10:40 UTC
I often use a local haxelib repo in my projects ( `.haxelib` folder created by command `haxelib newrepo` )

When displaying errors after a compilation and click on the error, VScode doesn't manage correctly the path of the file if its located in a haxelib : 

`Unable to open 'Main.hx' : File not found (file:///c:/projects/docker-cagette/app/C:/projects/docker-cagette/app/.haxelib/cagette-hosted/git/src/hosted/controller/Main.hx).`

however , it seems that complétion is also broken when I work on a file which is located in a haxelib.

**Comment by ncannasse** [comment] 2018-03-03 12:58
Duplicate of #23 , please close

**Closed** 2018-03-03 13:32 UTC
