### ISSUE TITLE
Error in -lib not clickable in problems

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#145] opened 2017-07-01 13:14 UTC
When having an error in one of the -lib files, the terminal correctly displays:

![image](https://user-images.githubusercontent.com/1022912/27762298-878bf08c-5eaa-11e7-9c1f-5b685e47f485.png)

But when clicking on the Problem I'm getting the following error:

![image](https://user-images.githubusercontent.com/1022912/27762302-a75226d4-5eaa-11e7-929a-7a0e31a34055.png)

Which is "impossible to open ...." (the path being wrong)

**Comment by Gama11** [comment] 2017-07-01 13:18
Duplicate of https://github.com/vshaxe/vshaxe/issues/23.

**Closed by Gama11** 2017-07-01 13:18 UTC
