### ISSUE TITLE
Incorrect syntax highlight

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/vshaxe#90] opened 2017-02-14 06:53 UTC
v1.3.1

The `'tickstart'` string:
<img width="451" alt="screen shot 2017-02-14 at 2 52 23 pm" src="https://cloud.githubusercontent.com/assets/1103788/22918417/43c8b35e-f2c5-11e6-9e7a-6a7f5c5a9516.png">

**Comment by Gama11** [comment] 2017-02-14 07:48
Probably a duplicate of https://github.com/vshaxe/haxe-TmLanguage/issues/3.

**Closed by Gama11** 2017-02-14 07:48 UTC
